add_newline = false # æ”¹è¡Œã®åæ˜ 
format = """
[â”Œâ”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€](bold purple)
[â”‚](bold green)[ $username](bold green)$aws [$time](bold red)
[â”‚](bold green)$directory  $git_status
[â””â”€â”€](bold green) $git_branch [$character](bold green) 
"""


[username]
style_user = "white dimmed"
style_root = "black bold"
format = "[$user]($style)"
disabled = false
show_always = true

[time]
disabled = false
format = '[$time](dimmed white) '
time_format = "%H:%M"
utc_time_offset = "+9"
time_range = "0:00-24:00"

[cmd_duration]
disabled = true
show_always = true

[character]
success_symbol = "[ğŸŸ \\$](white)" # normal prompt
error_symbol = "[ğŸ±ğŸ’¢ğŸ’¢ğŸ’¢](bold red)" # used if previous command failed

[directory]
format = " [$path]($style)"
style = "fg:cyan"
truncate_to_repo = false
truncation_length = 2 # parent directories to show; default is 3
truncation_symbol = "~/"

[git_branch]
format = "[â­‘ ]($style)[$branch]($style)"
style = "bold red"
symbol = "[ğŸ˜³] (bold green)" # normal prompt

[git_status]
format = "[$all_status$ahead_behind]($style)"
ahead = "â‡¡:$count "
behind = "â‡£:$count "
deleted = "ğŸ—‘:$count "
diverged = "ğŸŸ:$count "
stashed = "ğŸ“¦:$count "
modified = "ğŸ˜‚ :$count modified "
staged = '[ğŸ˜… $count ](dimmed bold green)'
renamed = "ğŸ˜‡ :$count "
untracked = ""
style = "dimmed bold red"

[aws] # $aws ã§å‘¼ã³å‡ºã—ã¦ã„ã‚‹
format = ' [on](white dimmed) [$symbol($profile)]($style)'
style = "bold blue"
symbol = "âœ¿ "
[aws.region_aliases]
ap-northeast-1 = "jp"
